d

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -42,19 +42,15 @@ jobs:
         env:
           LD_LIBRARY_PATH: /opt/intel/mkl/lib/intel64 
           CIBW_BEFORE_BUILD: |
-            export PKG_CONFIG_PATH="/home/runner/micromamba/envs/pyensmallen/lib/pkgconfig:$PKG_CONFIG_PATH"
-            export CMAKE_PREFIX_PATH="/home/runner/micromamba/envs/pyensmallen"
-            export OPENBLAS=/home/runner/micromamba/envs/pyensmallen/lib/libopenblas.so
-            export BLAS=$OPENBLAS
-            export LAPACK=$OPENBLAS
+            export PKG_CONFIG_PATH="/Users/runner/micromamba/envs/pyensmallen/lib/pkgconfig:$PKG_CONFIG_PATH"
+            export CMAKE_PREFIX_PATH="/Users/runner/micromamba/envs/pyensmallen"
+            ls -la /Users/runner/micromamba/envs/pyensmallen/lib/pkgconfig || echo "pkgconfig dir not found"
             python -m pip install -v build
             python -c "import os; print('Environment:', os.environ)"
           CIBW_ENVIRONMENT_LINUX: >-
             MAMBA_ROOT_PREFIX="/host/home/runner/micromamba"
             CMAKE_PREFIX_PATH="/host/home/runner/micromamba/envs/pyensmallen"
             VERBOSE=1
-            LD_LIBRARY_PATH: "/usr/lib/x86_64-linux-gnu:/opt/intel/mkl/lib/intel64:$LD_LIBRARY_PATH"
-
           CIBW_ENVIRONMENT_MACOS: >-
             PKG_CONFIG_PATH="/Users/runner/micromamba/envs/pyensmallen/lib/pkgconfig"
             CMAKE_PREFIX_PATH="/Users/runner/micromamba/envs/pyensmallen"
